Repository ManageIQ/manageiq-providers-redfish, pull requests merged in 2018-09, with the labels that each got.

#26 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#29 Move LED state from server to asset details
  app/models/manageiq/providers/redfish/inventory/collector/physical_infra_manager.rb
  app/models/manageiq/providers/redfish/inventory/parser/physical_infra_manager.rb
  spec/models/manageiq/providers/redfish/physical_infra_manager/refresher_spec.rb
Labels: bug

#32 Replace test data
  spec/models/manageiq/providers/redfish/physical_infra_manager/refresher_spec.rb
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_blink_loc_led/makes_location_LED_start_blinking.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_power_off/powers_off_the_system.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_power_off_now/powers_off_the_system_immediately.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_power_on/powers_on_the_system.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_restart/restarts_the_system.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_restart_now/restarts_the_system_immediately.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_turn_off_loc_led/turns_off_location_LED.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_turn_on_loc_led/turns_on_location_LED.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager_Refresher/refresh/will_perform_a_full_refresh.yml
Labels: test

#35 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation

#36 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation
