Repository ManageIQ/manageiq-providers-redfish, pull requests merged in 2018-06, with the labels that each got.

#3 Add redfish_tools gem development dependency
  manageiq-providers-redfish.gemspec
Labels: developer

#6 Add tests for asset details parsing
  spec/models/manageiq/providers/redfish/inventory/collector/physical_infra_manager_spec.rb
Labels: test

#5 Add power operations to physical server
  app/models/manageiq/providers/redfish/physical_infra_manager.rb
  app/models/manageiq/providers/redfish/physical_infra_manager/operations.rb
  app/models/manageiq/providers/redfish/physical_infra_manager/operations/power.rb
  spec/factories/ext_management_system.rb
  spec/factories/physical_server.rb
  spec/models/manageiq/providers/redfish/physical_infra_manager/operations/power_spec.rb
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_power_off/powers_off_the_system.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_power_off_now/powers_off_the_system_immediately.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_power_on/powers_on_the_system.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_restart/restarts_the_system.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_restart_now/restarts_the_system_immediately.yml
Labels: enhancement

#9 Add display name for physical server
  app/models/manageiq/providers/redfish/physical_infra_manager/physical_server.rb
Labels: enhancement

#10 Add hardware inventory refresh
  app/models/manageiq/providers/redfish/inventory/collector/physical_infra_manager.rb
  app/models/manageiq/providers/redfish/inventory/parser/physical_infra_manager.rb
  app/models/manageiq/providers/redfish/inventory/persister/physical_infra_manager.rb
  app/models/manageiq/providers/redfish/inventory_collection_default/physical_infra_manager.rb
  app/models/manageiq/providers/redfish/physical_infra_manager.rb
  spec/models/manageiq/providers/redfish/inventory/collector/physical_infra_manager_spec.rb
  spec/models/manageiq/providers/redfish/physical_infra_manager/refresher_spec.rb
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_blink_loc_led/makes_location_LED_start_blinking.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_power_off/powers_off_the_system.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_power_off_now/powers_off_the_system_immediately.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_power_on/powers_on_the_system.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_restart/restarts_the_system.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_restart_now/restarts_the_system_immediately.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_turn_off_loc_led/turns_off_location_LED.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager/_turn_on_loc_led/turns_on_location_LED.yml
  spec/vcr_cassettes/ManageIQ_Providers_Redfish_PhysicalInfraManager_Refresher/refresh/will_perform_a_full_refresh.yml
Labels: enhancement

#16 Lazy load PhysicalServer class in spec factory
  spec/factories/physical_server.rb
Labels: bug
