Repository ManageIQ/manageiq-providers-redfish, pull requests merged in 2019-11, with the labels that each got.

#97 Remove zanata from README
  README.md
Labels: cleanup

#99 Add params_for_create and verify_credentials
  app/models/manageiq/providers/redfish/manager_mixin.rb
Labels: enhancement

#100 Add CODEOWNERS
  .github/CODEOWNERS
Labels: documentation
