Repository ManageIQ/manageiq-providers-redfish, pull requests merged in 2019-01, with the labels that each got.

#46 Remove duplicated persister shared_options
  app/models/manageiq/providers/redfish/inventory/persister.rb
Labels: hammer/yes, refactoring

#47 Change FactoryGirl to FactoryBot
  spec/factories/ext_management_system.rb
  spec/factories/physical_server.rb
  spec/models/manageiq/providers/redfish/physical_infra_manager/operations/led_spec.rb
  spec/models/manageiq/providers/redfish/physical_infra_manager/operations/power_spec.rb
  spec/models/manageiq/providers/redfish/physical_infra_manager/refresher_spec.rb
  spec/models/manageiq/providers/redfish/physical_infra_manager_spec.rb
Labels: hammer/no, test

#48 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation
