Repository ManageIQ/manageiq-providers-redfish, pull requests merged in 2019-05, with the labels that each got.

#62 Physical server provisioning via StateMachine
  app/models/manageiq/providers/redfish/physical_infra_manager/physical_server.rb
  app/models/manageiq/providers/redfish/physical_infra_manager/physical_server/provisioning.rb
  app/models/manageiq/providers/redfish/physical_infra_manager/provision.rb
  app/models/manageiq/providers/redfish/physical_infra_manager/provision/state_machine.rb
  spec/models/manageiq/providers/redfish/physical_infra_manager/physical_server/provisioning_spec.rb
  spec/models/manageiq/providers/redfish/physical_infra_manager/provision/state_machine.rb
Labels: enhancement

#58 React Component that triggers Provisioning Request
  .babelrc
  .gitignore
  .npmrc
  .postcssrc.yml
  .travis.yml
  Rakefile
  app/helpers/manageiq/providers/redfish/toolbar_overrides/physical_server_center.rb
  app/helpers/manageiq/providers/redfish/toolbar_overrides/physical_servers_center.rb
  app/javascript/components/forms/pxe-details.jsx
  app/javascript/components/redfish-server-provision-dialog.jsx
  app/javascript/packs/component-definition-common.js
  app/javascript/utils/api.js
  package.json
  spec/javascript/components/__snapshots__/redfish-server-provision-dialog.test.jsx.snap
  spec/javascript/components/forms/__snapshots__/pxe-details.test.jsx.snap
  spec/javascript/components/forms/pxe-details.test.jsx
  spec/javascript/components/redfish-server-provision-dialog.test.jsx
  spec/javascript/setup.js
Labels: enhancement

#64 Change plugin common methods to class methods
  lib/manageiq/providers/redfish/engine.rb
Labels: refactoring

#63 Bump master travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#65 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#68 Suffix spec file with _spec.rb to actually test it
  spec/models/manageiq/providers/redfish/physical_infra_manager/provision/state_machine_spec.rb
Labels: test
