Repository ManageIQ/manageiq-providers-redfish, pull requests merged in 2020-09, with the labels that each got.

#119 Update DDF schema to version 2
  app/javascript/components/firmware-update.schema.js
  app/javascript/components/redfish-server-firmware-update-dialog.jsx
  app/javascript/components/redfish-server-provision-dialog.jsx
  app/javascript/components/server-provision.schema.js
  app/models/manageiq/providers/redfish/manager_mixin.rb
Labels: enhancement

#120 [JANSA] yarn upgrade: upgrade JS dependencies
  yarn.lock
Labels: dependencies, jansa/yes

#122 Make the default credentials required in the provider DDF
  app/models/manageiq/providers/redfish/manager_mixin.rb
Labels: bug

#123 Prefer ManageIQ::Password over legacy MiqPassword constant
  app/models/manageiq/providers/redfish/manager_mixin.rb
Labels: enhancement
