Repository ManageIQ/manageiq-providers-redfish, pull requests merged in 2020-05, with the labels that each got.

#106 Fix the loading of customization templates in the provisioning form
  app/javascript/components/redfish-server-provision-dialog.jsx
Labels: bug

#108 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#109 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#107 Convert final-form forms to DDF and get rid of react-ui-components
  .travis.yml
  Rakefile
  app/javascript/components/firmware-update.schema.js
  app/javascript/components/forms/firmware-update.jsx
  app/javascript/components/forms/pxe-details.jsx
  app/javascript/components/redfish-server-firmware-update-dialog.jsx
  app/javascript/components/redfish-server-provision-dialog.jsx
  app/javascript/components/server-provision.schema.js
  app/javascript/utils/api.js
  package.json
  spec/javascript/components/__snapshots__/redfish-server-firmware-update-dialog.test.jsx.snap
  spec/javascript/components/__snapshots__/redfish-server-provision-dialog.test.jsx.snap
  spec/javascript/components/forms/__snapshots__/firmware-update.test.jsx.snap
  spec/javascript/components/forms/__snapshots__/pxe-details.test.jsx.snap
  spec/javascript/components/forms/firmware-update.test.jsx
  spec/javascript/components/forms/pxe-details.test.jsx
  spec/javascript/components/redfish-server-firmware-update-dialog.test.jsx
  spec/javascript/components/redfish-server-provision-dialog.test.jsx
  spec/javascript/setup.js
  spec/other/travis_spec.rb
Labels: cleanup

#110 package.json: fix JSON syntax error (trailing comma)
  package.json
Labels: bug, cleanup

#114 Logout after collecting inventory
  app/models/manageiq/providers/redfish/inventory/collector.rb
  app/models/manageiq/providers/redfish/inventory/collector/physical_infra_manager.rb
  spec/models/manageiq/providers/redfish/inventory/parser/physical_infra_manager_spec.rb
Labels: bug
