Repository ManageIQ/manageiq-providers-redfish, pull requests merged in 2024-02, with the labels that each got.

#187 Drop require_nested and include_concern
  app/models/manageiq/providers/redfish/inventory.rb
  app/models/manageiq/providers/redfish/inventory/collector.rb
  app/models/manageiq/providers/redfish/inventory/parser.rb
  app/models/manageiq/providers/redfish/inventory/persister.rb
  app/models/manageiq/providers/redfish/physical_infra_manager.rb
  app/models/manageiq/providers/redfish/physical_infra_manager/event_catcher.rb
  app/models/manageiq/providers/redfish/physical_infra_manager/firmware_update_task.rb
  app/models/manageiq/providers/redfish/physical_infra_manager/operations.rb
  app/models/manageiq/providers/redfish/physical_infra_manager/physical_server.rb
  app/models/manageiq/providers/redfish/physical_infra_manager/provision.rb
  app/models/manageiq/providers/redfish/physical_infra_manager/refresh_worker.rb
Labels: technical debt, rails7

#188 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#189 Handle `nil` Chassis Members
  app/models/manageiq/providers/redfish/inventory/collector/physical_infra_manager.rb
Labels: bug

#190 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1
